/***** This file contains automatically generated code ******
**
** The code in this file has been automatically generated by
**
**   sqlite/tool/mkkeywordhash.c
**
** The code in this file implements a function that determines whether
** or not a given identifier is really an SQL keyword.  The same thing
** might be implemented more directly using a hand-written hash table.
** But by using this automatically generated code, the size of the code
** is substantially reduced.  This is important for embedded applications
** on platforms with limited memory.
*/
/* Hash score: 116 */
static int keywordCode(const char *z, int n, int *pType){
  /* zText[] encodes 568 bytes of keywords in 380 bytes */
  /*   CONSTRAINTOFFSETABLEFTHENDESCAPELSELECTRANSACTIONATURALLIKEY       */
  /*   SAVEPOINTEMPORARYWITHOUTERELEASEXCLUSIVEXISTSBEGINDEXEDELETE       */
  /*   BETWEENOTNULLIMITCASECOLLATECREATECURRENT_DATEGROUPDATEIGNORE      */
  /*   CURSIVEIMMEDIATEJOINNEREGEXPRIMARYMATCHECKVALUESWHENWHEREPLACE     */
  /*   ABORTANDEFAULTASCOMMITCONFLICTCROSSCURRENT_TIMESTAMPDEFERRED       */
  /*   ISTINCTDROPFAILFROMFULLGLOBYHAVINGIFINSERTISNULLORDERIGHT          */
  /*   ROLLBACKUNIQUEUSING                                                */
  static const char zText[379] = {
    'C','O','N','S','T','R','A','I','N','T','O','F','F','S','E','T','A','B',
    'L','E','F','T','H','E','N','D','E','S','C','A','P','E','L','S','E','L',
    'E','C','T','R','A','N','S','A','C','T','I','O','N','A','T','U','R','A',
    'L','L','I','K','E','Y','S','A','V','E','P','O','I','N','T','E','M','P',
    'O','R','A','R','Y','W','I','T','H','O','U','T','E','R','E','L','E','A',
    'S','E','X','C','L','U','S','I','V','E','X','I','S','T','S','B','E','G',
    'I','N','D','E','X','E','D','E','L','E','T','E','B','E','T','W','E','E',
    'N','O','T','N','U','L','L','I','M','I','T','C','A','S','E','C','O','L',
    'L','A','T','E','C','R','E','A','T','E','C','U','R','R','E','N','T','_',
    'D','A','T','E','G','R','O','U','P','D','A','T','E','I','G','N','O','R',
    'E','C','U','R','S','I','V','E','I','M','M','E','D','I','A','T','E','J',
    'O','I','N','N','E','R','E','G','E','X','P','R','I','M','A','R','Y','M',
    'A','T','C','H','E','C','K','V','A','L','U','E','S','W','H','E','N','W',
    'H','E','R','E','P','L','A','C','E','A','B','O','R','T','A','N','D','E',
    'F','A','U','L','T','A','S','C','O','M','M','I','T','C','O','N','F','L',
    'I','C','T','C','R','O','S','S','C','U','R','R','E','N','T','_','T','I',
    'M','E','S','T','A','M','P','D','E','F','E','R','R','E','D','I','S','T',
    'I','N','C','T','D','R','O','P','F','A','I','L','F','R','O','M','F','U',
    'L','L','G','L','O','B','Y','H','A','V','I','N','G','I','F','I','N','S',
    'E','R','T','I','S','N','U','L','L','O','R','D','E','R','I','G','H','T',
    'R','O','L','L','B','A','C','K','U','N','I','Q','U','E','U','S','I','N',
    'G',
  };
  static const unsigned char aHash[127] = {
      81,  72,  85,  50,   0,  24,   0,   0,  57,   0,  55,   0,   0,
       6,  48,   0,  34,   0,  84,  58,  79,  80,   0,  15,   0,   0,
      22,   0,  20,   0,   0,  53,   4,   0,   0,   0,   0,  43,  44,
       0,  42,   0,   0,   0,  62,  54,   0,  64,  69,   0,   0,  31,
       0,  70,   0,   0,   0,   0,  36,   0,  11,   0,  13,  77,  14,
       0,   0,   0,  19,  73,  37,   0,  33,  56,  46,   0,  63,   0,
      68,   0,   0,  67,   0,   0,   0,   0,   0,  65,   0,  76,   0,
       1,  75,   0,  61,   0,  30,  60,  78,   0,   0,  87,   0,  82,
      39,  25,  41,   0,   0,   3,   2,  49,  83,   0,   0,   0,   0,
      17,   0,  59,  52,  40,   0,   8,  38,   0,  86,
  };
  static const unsigned char aNext[87] = {
       0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  12,
       0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   9,   0,
       0,   0,  27,   0,  23,   0,   0,   0,   0,   0,   0,  18,   0,
       0,   0,   0,   0,   0,   0,  35,   0,   0,   0,   0,   5,   0,
      10,   0,   0,   0,  26,   0,   0,  29,   0,   0,  32,   0,   0,
       0,   0,   0,  45,   0,  21,   0,  71,  66,   0,  74,   0,   0,
       7,   0,   0,  51,  28,  16,   0,  47,   0,
  };
  static const unsigned char aLen[87] = {
      10,   4,   2,   2,   6,   2,   3,   5,   4,   4,   3,   4,   6,
       4,   6,  11,   2,   7,   3,   4,   3,   9,   9,   4,   2,   7,
       4,   5,   7,   2,   9,   6,   5,   7,   5,   6,   7,   7,   3,
       4,   5,   4,   7,   6,  12,   5,   6,   6,   9,   9,   4,   5,
       6,   7,   5,   5,   6,   4,   5,   7,   5,   3,   7,   3,   6,
       8,   5,  17,  12,   8,   8,   2,   4,   4,   4,   4,   4,   2,
       6,   2,   6,   6,   5,   5,   8,   6,   5,
  };
  static const unsigned short int aOffset[87] = {
       0,   7,   7,   9,  10,  10,  13,  15,  18,  21,  23,  25,  26,
      31,  33,  38,  47,  48,  53,  55,  57,  60,  68,  68,  72,  77,
      77,  81,  85,  89,  91,  99, 105, 108, 108, 114, 120, 126, 126,
     129, 132, 137, 141, 148, 154, 166, 169, 175, 179, 188, 197, 199,
     203, 208, 215, 218, 223, 229, 233, 236, 243, 248, 250, 257, 259,
     265, 273, 278, 278, 295, 302, 303, 310, 314, 318, 322, 326, 329,
     331, 337, 339, 345, 351, 355, 360, 368, 374,
  };
  static const unsigned char aCode[87] = {
    TK_CONSTRAINT, TK_INTO,       TK_IN,         TK_TO,         TK_OFFSET,     
    TK_OF,         TK_SET,        TK_TABLE,      TK_JOIN_KW,    TK_THEN,       
    TK_END,        TK_DESC,       TK_ESCAPE,     TK_ELSE,       TK_SELECT,     
    TK_TRANSACTION,TK_ON,         TK_JOIN_KW,    TK_ALL,        TK_LIKE_KW,    
    TK_KEY,        TK_SAVEPOINT,  TK_TEMP,       TK_TEMP,       TK_OR,         
    TK_WITHOUT,    TK_WITH,       TK_JOIN_KW,    TK_RELEASE,    TK_AS,         
    TK_EXCLUSIVE,  TK_EXISTS,     TK_BEGIN,      TK_INDEXED,    TK_INDEX,      
    TK_DELETE,     TK_BETWEEN,    TK_NOTNULL,    TK_NOT,        TK_NULL,       
    TK_LIMIT,      TK_CASE,       TK_COLLATE,    TK_CREATE,     TK_CTIME_KW,   
    TK_GROUP,      TK_UPDATE,     TK_IGNORE,     TK_RECURSIVE,  TK_IMMEDIATE,  
    TK_JOIN,       TK_JOIN_KW,    TK_LIKE_KW,    TK_PRIMARY,    TK_MATCH,      
    TK_CHECK,      TK_VALUES,     TK_WHEN,       TK_WHERE,      TK_REPLACE,    
    TK_ABORT,      TK_AND,        TK_DEFAULT,    TK_ASC,        TK_COMMIT,     
    TK_CONFLICT,   TK_JOIN_KW,    TK_CTIME_KW,   TK_CTIME_KW,   TK_DEFERRED,   
    TK_DISTINCT,   TK_IS,         TK_DROP,       TK_FAIL,       TK_FROM,       
    TK_JOIN_KW,    TK_LIKE_KW,    TK_BY,         TK_HAVING,     TK_IF,         
    TK_INSERT,     TK_ISNULL,     TK_ORDER,      TK_JOIN_KW,    TK_ROLLBACK,   
    TK_UNIQUE,     TK_USING,      
  };
  int i, j;
  const char *zKW;
  if( n>=2 ){
    i = ((charMap(z[0])*4) ^ (charMap(z[n-1])*3) ^ n) % 127;
    for(i=((int)aHash[i])-1; i>=0; i=((int)aNext[i])-1){
      if( aLen[i]!=n ) continue;
      j = 0;
      zKW = &zText[aOffset[i]];
#ifdef SQLITE_ASCII
      while( j<n && (z[j]&~0x20)==zKW[j] ){ j++; }
#endif
#ifdef SQLITE_EBCDIC
      while( j<n && toupper(z[j])==zKW[j] ){ j++; }
#endif
      if( j<n ) continue;
      testcase( i==0 ); /* CONSTRAINT */
      testcase( i==1 ); /* INTO */
      testcase( i==2 ); /* IN */
      testcase( i==3 ); /* TO */
      testcase( i==4 ); /* OFFSET */
      testcase( i==5 ); /* OF */
      testcase( i==6 ); /* SET */
      testcase( i==7 ); /* TABLE */
      testcase( i==8 ); /* LEFT */
      testcase( i==9 ); /* THEN */
      testcase( i==10 ); /* END */
      testcase( i==11 ); /* DESC */
      testcase( i==12 ); /* ESCAPE */
      testcase( i==13 ); /* ELSE */
      testcase( i==14 ); /* SELECT */
      testcase( i==15 ); /* TRANSACTION */
      testcase( i==16 ); /* ON */
      testcase( i==17 ); /* NATURAL */
      testcase( i==18 ); /* ALL */
      testcase( i==19 ); /* LIKE */
      testcase( i==20 ); /* KEY */
      testcase( i==21 ); /* SAVEPOINT */
      testcase( i==22 ); /* TEMPORARY */
      testcase( i==23 ); /* TEMP */
      testcase( i==24 ); /* OR */
      testcase( i==25 ); /* WITHOUT */
      testcase( i==26 ); /* WITH */
      testcase( i==27 ); /* OUTER */
      testcase( i==28 ); /* RELEASE */
      testcase( i==29 ); /* AS */
      testcase( i==30 ); /* EXCLUSIVE */
      testcase( i==31 ); /* EXISTS */
      testcase( i==32 ); /* BEGIN */
      testcase( i==33 ); /* INDEXED */
      testcase( i==34 ); /* INDEX */
      testcase( i==35 ); /* DELETE */
      testcase( i==36 ); /* BETWEEN */
      testcase( i==37 ); /* NOTNULL */
      testcase( i==38 ); /* NOT */
      testcase( i==39 ); /* NULL */
      testcase( i==40 ); /* LIMIT */
      testcase( i==41 ); /* CASE */
      testcase( i==42 ); /* COLLATE */
      testcase( i==43 ); /* CREATE */
      testcase( i==44 ); /* CURRENT_DATE */
      testcase( i==45 ); /* GROUP */
      testcase( i==46 ); /* UPDATE */
      testcase( i==47 ); /* IGNORE */
      testcase( i==48 ); /* RECURSIVE */
      testcase( i==49 ); /* IMMEDIATE */
      testcase( i==50 ); /* JOIN */
      testcase( i==51 ); /* INNER */
      testcase( i==52 ); /* REGEXP */
      testcase( i==53 ); /* PRIMARY */
      testcase( i==54 ); /* MATCH */
      testcase( i==55 ); /* CHECK */
      testcase( i==56 ); /* VALUES */
      testcase( i==57 ); /* WHEN */
      testcase( i==58 ); /* WHERE */
      testcase( i==59 ); /* REPLACE */
      testcase( i==60 ); /* ABORT */
      testcase( i==61 ); /* AND */
      testcase( i==62 ); /* DEFAULT */
      testcase( i==63 ); /* ASC */
      testcase( i==64 ); /* COMMIT */
      testcase( i==65 ); /* CONFLICT */
      testcase( i==66 ); /* CROSS */
      testcase( i==67 ); /* CURRENT_TIMESTAMP */
      testcase( i==68 ); /* CURRENT_TIME */
      testcase( i==69 ); /* DEFERRED */
      testcase( i==70 ); /* DISTINCT */
      testcase( i==71 ); /* IS */
      testcase( i==72 ); /* DROP */
      testcase( i==73 ); /* FAIL */
      testcase( i==74 ); /* FROM */
      testcase( i==75 ); /* FULL */
      testcase( i==76 ); /* GLOB */
      testcase( i==77 ); /* BY */
      testcase( i==78 ); /* HAVING */
      testcase( i==79 ); /* IF */
      testcase( i==80 ); /* INSERT */
      testcase( i==81 ); /* ISNULL */
      testcase( i==82 ); /* ORDER */
      testcase( i==83 ); /* RIGHT */
      testcase( i==84 ); /* ROLLBACK */
      testcase( i==85 ); /* UNIQUE */
      testcase( i==86 ); /* USING */
      *pType = aCode[i];
      break;
    }
  }
  return n;
}
int sqlite3KeywordCode(const unsigned char *z, int n){
  int id = TK_ID;
  keywordCode((char*)z, n, &id);
  return id;
}
#define SQLITE_N_KEYWORD 87
